# quarkus config
quarkus.http.enable-compression=true
quarkus.http.port=8080

# logging config
quarkus.log.category."org.ivione93".level=INFO

%dev.quarkus.console.color=true
%dev.quarkus.log.console.level=DEBUG
%dev.quarkus.log.console.json=false
%dev.quarkus.log.category."org.ivione93".level=DEBUG
%dev.quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG

%test.quarkus.log.console.json=false
%test.quarkus.log.category."org.ivione93".level=INFO

# rest client
%dev.quarkus.rest-client.logging.scope=request-response
%dev.quarkus.rest-client.logging.body-limit=9999
%dev.quarkus.rest-client.extensions-api.scope=all

quarkus.rest-client.rickmorty.url=https://rickandmortyapi.com
quarkus.rest-client.rickmorty.scope=jakarta.enterprise.context.ApplicationScoped

api.timeout.milliseconds=3000